---
- name: install docker
  hosts: docker_machines
  gather_facts: false
  roles:
    - dependency
    - add_repo
    - install_docker
    - service
    - firewall

- name: init swarm
  
  hosts: swarm_master
  roles:
      - role: swarm_init
        tags: init
- hosts: swarm_managers
  vars:
    swarm_master_pass: 'root'
    swarm_join_addr: "192.168.75.11:2377"
    swarm_master: "192.168.75.11"
  roles:
      - role: swarm_manager
        
    #  - portainer
- hosts: swarm_workers
  vars:
    swarm_master_pass: 'root'
    swarm_join_addr: "192.168.75.11:2377"
    swarm_master: "192.168.75.11"
  roles:
      - role: swarm_worker
        tags: init
