---

- name: swarm init
  shell: |
    docker swarm init --advertise-addr {{ inventory_hostname }} --data-path-addr {{ inventory_hostname }}
  register: result
  ignore_errors: yes

- name: manager token
  shell: |
    docker swarm join-token manager -q > /root/manager_token.txt
  register: manager

- name: swarm group
  shell: |
    docker swarm join-token worker -q > /root/worker_token.txt
  register: worker

- set_fact:
    swarm_join_addr: "{{ inventory_hostname }}:2377"
    manager: "{{ manager.stdout }}"
    swarmworker_token: "{{ worker.stdout }}"       
      