
- name: copy token
  shell: >
          sshpass -p {{ swarm_master_pass }} scp -o StrictHostKeyChecking=no \
          -o NoHostAuthenticationForLocalhost=yes -o UserKnownHostsFile=/dev/null \
           {{ swarm_master }}:/root/worker_token.txt /root/
- name: join swarm as a worker
  shell: |
    docker swarm join --token  $(cat /root/worker_token.txt) "{{ swarm_join_addr }}"


  
  register: result
  failed_when:
    - result.rc != 0
    - '"This node is already part of a swarm " not in result.stderr'

 